# Site
repository: BryanLX/BryanLX.github.io
favicon: images/favicon.png

# Personal info
name: Bryan Liu
title: Software Developer
email: binliu321@gmail.com
website: https://github.com/BryanLX

# Social links
twitter_username: None
github_username:  BryanLX
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: brianliuisme
linkedin_username: bryan-bin-liu-ab312b134
# pinterest_username: jekyll
youtube_username: channel/UCD1YU5o1Het_k-SDp4bLa2Q
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a passionate, knowledgable, and solutions-focused Software Developer with a BSc in Computer Science and 2+
  years of experience with full stack software development and enhancement,
  Recognized as a strategic problem-solver with a demonstrated record of defining, building, and implementing solutions that drive product improvements and ensure current and future business needs are met. 
  Proven history of contributing to all aspects of project development – from initial design and planning through to delivery and integration. Adept at working within a team or independently in fast-paced environments while balancing multiple tasks and competing deadlines.

  <h2>Skills:</h2> <mark>Full Stack Software Development</mark>, <mark>System & Architecture Design</mark>, <mark>Object-Oriented Programming</mark>, <mark>Troubleshooting & Testing</mark>, <mark>Requirements Gathering</mark>, <mark>Multitasking & Prioritization</mark>, <mark>Agile & Scrum Methodologies</mark>, <mark>Team Leadership & Building</mark>, <mark> Documentation & Reporting</mark>

  <h2>Technical Expertise:</h2> <mark>Java</mark>, <mark>Python</mark>, <mark>JavaScript</mark>, <mark>C#</mark>, <mark>Python</mark>, <mark>ASP.NET</mark>, <mark>CSS</mark>, <mark>SQL</mark>, <mark>SVN</mark>, <mark>Git</mark>, <mark>Angular</mark>, <mark>Node.Js</mark>, <mark>AWS Lambda</mark>, <mark>DynamoDb</mark>, <mark>Soap</mark>, <mark>JQuery</mark>, <mark>Swing</mark>, <mark>MS Office Suite</mark>, <mark>Google Suite</mark>, <mark>Linux</mark>, <mark>Unix</mark>

  <h2>Languages:</h2> <mark>English</mark>, <mark>Mandarin


# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience


# Projects Section
# projects_title: Projects



# More Section
more_title: Ceritfications
more_content: | # this will include new lines to allow paragraphs
  - Amazon Web Services Developer - Associate     
  <img src="AWScert.jpg" alt="text" width="1000" height="800"/>
  - Amazon Web Services Cloud Practitioner   
  <img src="AWScert2.jpg" alt="text" width="1000" height="800"/>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
