# Site
repository: BryanLX/BryanLX.github.io
favicon: images/favicon.ico

# Personal info
name: Bryan Liu
title: Software Developer
email: binliu321@gmail.com
website: https://github.com/BryanLX

# Social links
twitter_username: None
github_username:  BryanLX
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: brianliuisme
linkedin_username: bryan-bin-liu-ab312b134
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a passionate, knowledgable, and solutions-focused Software Developer with a BSc in Computer Science and 2+
  years of experience with full stack software development and enhancement,
  Recognized as a strategic problem-solver with a demonstrated record of defining, building, and implementing solutions that drive product improvements and ensure current and future business needs are met. 
  Proven history of contributing to all aspects of project development – from initial design and planning through to delivery and integration. Adept at working within a team or independently in fast-paced environments while balancing multiple tasks and competing deadlines.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
